diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: "front_left_wheel_joint"
  right_wheel: "front_right_wheel_joint"
  wheel_separation: 0.5
  wheel_radius: 0.1
  command_topic: "controller_input"
  publish_rate: 50

controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    gazebo_ros2_control:
      type: gazebo_ros2_control/GazeboSystem

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

    wheel_separation: 0.55
    wheel_radius: 0.15

    # Increased speed limits
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 2.0  # Increased from 0.5 to 2.0
    linear.x.min_velocity: -2.0  # Increased from -0.5 to -2.0
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 1.0  # Increased from 0.25 to 1.0
    linear.x.min_acceleration: -1.0  # Increased from -0.25 to -1.0

    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 2.0  # Increased from 1.0 to 2.0
    angular.z.min_velocity: -2.0  # Increased from -1.0 to -2.0
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 1.0  # Increased from 0.5 to 1.0
    angular.z.min_acceleration: -1.0  # Increased from -0.5 to -1.0

    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    
    wheels_per_side: 2
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    
    enable_odom_tf: true
    
    base_frame_id: base_link
    odom_frame_id: odom
    
    publish_limited_velocity: true
    use_stamped_vel: false